import 'package:akwe/src/models/banking.dart';

getBankInstitution() {
  var inAppBankList = [
    Bank(
        1, "Banco do Brasil", "assets/banks/logo-banco-do-brasil-icon-256.png"),
    Bank(4, "BNB", "assets/banks/Banco_do_Nordeste.png"),
    Bank(33, "Santander", "assets/banks/Santander_logo_PNG2.png"),
    Bank(36, "Bradesco", "assets/banks/Bradesco_logo_PNG3.png"),
    Bank(41, "Banrisul", "assets/banks/logo-banrisul-1536.png"),
    Bank(62, "Hipercard", "assets/banks/logo-hipercard-1024.png"),
    Bank(69, "Crefisa", "assets/banks/crefisa-1024.png"),
    Bank(74, "Safra", "assets/banks/logo-banco-safra-icon-256.png"),
    Bank(77, "Banco Inter", "assets/banks/logo-banco-inter-1536.png"),
    Bank(79, "Picpay", "assets/banks/logo-picpay-1024.png"),
    Bank(102, "Xp Investimentos",
        "assets/banks/logo-xp-investimentos-icon-256.png"),
    Bank(104, "Caixa", "assets/banks/logo-caixa-economica-federal-1536.png"),
    Bank(121, "Agibank", "assets/banks/logo-agibank-icon-1536.png"),
    Bank(184, "Itaú", "assets/banks/logo-itau-1536.png"),
    Bank(208, "BTG Pactual", "assets/banks/btg-pactual-1024.png"),
    Bank(212, "Original", "assets/banks/logo-banco-original-1536.png"),
    Bank(269, "HSBC", "assets/banks/logo-HSBC-256.png"),
    Bank(280, "Banco will", "assets/banks/will-bank-1024.png"),
    Bank(286, "Nubank", "assets/banks/logo-nubank-roxo-icon-256.png"),
    Bank(318, "BMG", "assets/banks/logo-banco-bmg-1536.png"),
    Bank(335, "Digio", "assets/banks/logo-digio-1536.png"),
    Bank(336, "C6 Bank", "assets/banks/logo-c6-bank-1024.png"),
    Bank(342, "Creditas", "assets/banks/creditas-1024.png"),
    Bank(362, "Cielo", "assets/banks/logo-cielo-1024.png"),
    Bank(383, "Ebanx", "assets/banks/ebanx-1024.png"),
    Bank(426, "Neon", "assets/banks/neon-1024.png"),
    Bank(477, "Citibank", "assets/banks/logo-citi-256.png"),
    Bank(748, "Sicredi", "assets/banks/logo-sicredi-icon-256.png"),
    Bank(654, "A.J. RENNER S.A.",
        "assets/banks/logo-renner-fundo-vermelho-512.png"),
    Bank(7001, "Alelo", "assets/banks/alelo-1024.png"),
    Bank(7003, "Vale Refeição", "assets/banks/logo-vr-vale-refeicao-1536.png"),
    Bank(7005, "Agora Investimentos",
        "assets/banks/logo-agora-investimentos-1536.png"),
    Bank(7007, "American Express",
        "assets/banks/American_Express_logo_PNG1.png"),
    Bank(7009, "Ben Visa Vale", "assets/banks/ben-visa-vale-256.png"),
    Bank(7011, "BanesCard", "assets/banks/banescard-1024.png"),
    Bank(7013, "Banco de Brasília",
        "assets/banks/brb-banco-de-brasilia-1024.png"),
    Bank(7015, "Binance", "assets/banks/Binance_logo_PNG4.png"),
    Bank(7017, "Bitcoin", "assets/banks/Bitcoin_logo_PNG1.png"),
    Bank(7019, "Cash Me", "assets/banks/cashme-1024.png"),
    Bank(7021, "Clear Corretora",
        "assets/banks/logo-clear-corretora-horizontal-256.png"),
    Bank(
        7023, "Diners", "assets/banks/Diners_Club_International_logo_PNG5.png"),
    Bank(7025, "Elo", "assets/banks/Elo_logo_PNG1.png"),
    Bank(7027, "Hotmart", "assets/banks/logo-hotmart-icone-1024.png"),
    Bank(7029, "Mastercard", "assets/banks/logo-mastercard-256.png"),
    Bank(7031, "Monetizze", "assets/banks/logo-monetizze-1024.png"),
    Bank(7033, "Next", "assets/banks/banco-next-1536.png"),
    Bank(7035, "Nu invest", "assets/banks/logo-nubank-roxo-icon-1536.png"),
    Bank(7037, "PagBank", "assets/banks/PagSeguro-Logo-PNG2.png"),
    Bank(7039, "Pagseguro", "assets/banks/PagSeguro-Logo-PNG2.png"),
    Bank(7041, "PayPal", "assets/banks/logo-paypal-256.png"),
    Bank(7043, "Rico", "assets/banks/logo-rico-1024.png"),
    Bank(7045, "Société Générale",
        "assets/banks/Societe_Generale_logo_PNG2.png"),
    Bank(7047, "Visa", "assets/banks/logo-visa-256.png"),
    Bank(7070, "Carteira", "assets/banks/wallet_PNG77083.png"),
    Bank(7080, "Google Pay", "assets/banks/logo-google-pay-512.png"),
    Bank(7090, "Payoneer", "assets/banks/payoneer-512.png"),
    Bank(8000, "99 Pay", "assets/banks/logo-99pay.png"),
  ];

  return inAppBankList;
}
