// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGMcvJrm5NpZUhONf-0FKaUWiX1dibJU',
    appId: '1:669387745363:web:6786237c28a1c59aba7ea6',
    messagingSenderId: '669387745363',
    projectId: 'akwe-dev',
    authDomain: 'akwe-dev.firebaseapp.com',
    storageBucket: 'akwe-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2mvNMm2GFT1WAJW7SPWH9U_xLe3vLEE',
    appId: '1:669387745363:android:7b00adbf19d5b619ba7ea6',
    messagingSenderId: '669387745363',
    projectId: 'akwe-dev',
    storageBucket: 'akwe-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBvTbqeq9nC0xsKPOPLUvbjUwYm_Bgbs',
    appId: '1:669387745363:ios:c1c86c1de3e1566dba7ea6',
    messagingSenderId: '669387745363',
    projectId: 'akwe-dev',
    storageBucket: 'akwe-dev.firebasestorage.app',
    iosBundleId: 'com.wanubit.akwe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBvTbqeq9nC0xsKPOPLUvbjUwYm_Bgbs',
    appId: '1:669387745363:ios:c1c86c1de3e1566dba7ea6',
    messagingSenderId: '669387745363',
    projectId: 'akwe-dev',
    storageBucket: 'akwe-dev.firebasestorage.app',
    iosBundleId: 'com.wanubit.akwe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSGMcvJrm5NpZUhONf-0FKaUWiX1dibJU',
    appId: '1:669387745363:web:231a5993fdf67b87ba7ea6',
    messagingSenderId: '669387745363',
    projectId: 'akwe-dev',
    authDomain: 'akwe-dev.firebaseapp.com',
    storageBucket: 'akwe-dev.firebasestorage.app',
  );
}
