// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1DA6IDiJ9QuqNkednG10ZhEdfASd50Y',
    appId: '1:608266063758:web:dd1d897973b30d8a591edf',
    messagingSenderId: '608266063758',
    projectId: 'akwe-prod',
    authDomain: 'akwe-prod.firebaseapp.com',
    storageBucket: 'akwe-prod.firebasestorage.app',
    measurementId: 'G-V0J8N3MFBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKxen04fYyvIeWaS48ykQbwXKX_fQHlQ8',
    appId: '1:608266063758:android:a150f7d8866479fe591edf',
    messagingSenderId: '608266063758',
    projectId: 'akwe-prod',
    storageBucket: 'akwe-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChg6_BkZO8dXb4e3CDjBgrBPwUo4Z0Vgk',
    appId: '1:608266063758:ios:c5eb57028e5412dd591edf',
    messagingSenderId: '608266063758',
    projectId: 'akwe-prod',
    storageBucket: 'akwe-prod.firebasestorage.app',
    iosBundleId: 'com.wanubit.akwe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChg6_BkZO8dXb4e3CDjBgrBPwUo4Z0Vgk',
    appId: '1:608266063758:ios:c5eb57028e5412dd591edf',
    messagingSenderId: '608266063758',
    projectId: 'akwe-prod',
    storageBucket: 'akwe-prod.firebasestorage.app',
    iosBundleId: 'com.wanubit.akwe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1DA6IDiJ9QuqNkednG10ZhEdfASd50Y',
    appId: '1:608266063758:web:15601ce86efd1069591edf',
    messagingSenderId: '608266063758',
    projectId: 'akwe-prod',
    authDomain: 'akwe-prod.firebaseapp.com',
    storageBucket: 'akwe-prod.firebasestorage.app',
    measurementId: 'G-BYPZCZ3T33',
  );
}
