/// Flutter icons WanuFonts
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WanuFonts
///      fonts:
///       - asset: fonts/WanuFonts.ttf
///
/// 
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class WanuIcons {
  WanuIcons._();

  static const _kFontFam = 'WanuFonts';
  static const String? _kFontPkg = null;

  static const binance = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const icon_99_app = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const pix_banco_central = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const ifood_43 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
